server:
 port: 48081

redis:
    cluster:
      nodes: 192.168.0.53:40101   # 单机或集群节点
    password:  # 单机或集群密码
    lettuce:
      shutdown-timeout: 100 # 关闭超时时间
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        maxTotal: 8  #最大连接数量

#日志配置
log:
 path: ../logs
 level: INFO
